/* Local-only presentation interactions. No analytics, provider calls or payment flows. */
(()=>{'use strict';
const $=id=>document.getElementById(id), E=window.BeGlobalEconomics;
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const decimal=n=>new Intl.NumberFormat('es-MX',{maximumFractionDigits:1}).format(n);
const put=(id,value)=>{$(id).textContent=value;};
let currentModel=null;
function readForm(){return Object.fromEntries(Object.keys(E.defaults).map(k=>[k,$(k).value]));}
function calculate(){try{const m=E.program(readForm());currentModel=m;$('model-error').hidden=true;$('model-results').hidden=false;$('export-scenario').disabled=false;put('revenue',money(m.revenue));put('variable-total',money(m.variableTotal));put('reserve-total',money(m.reserveTotal));put('fixed-total',money(m.fixed));put('profit',money(m.profit));$('profit').classList.toggle('negative',m.profit<0);put('beglobal-share',money(m.beglobal));put('softvibes-share',money(m.softvibes));put('share-label',decimal(m.share)+'%');put('softvibes-label',decimal(100-m.share)+'%');put('break-even',m.breakEven===null?'No alcanzable con estos supuestos':decimal(m.breakEven)+' miembros');put('net-beglobal',money(m.netBeglobal));$('net-beglobal').classList.toggle('negative',m.netBeglobal<0);const tbody=$('scenario-table');tbody.replaceChildren();for(const members of[50,100,300]){const row=E.program({...m,members}),tr=document.createElement('tr');for(const value of[decimal(members),money(row.revenue),money(row.profit),money(row.beglobal)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}tbody.append(tr);}}catch(e){currentModel=null;put('model-error',e.message);$('model-error').hidden=false;$('model-results').hidden=true;$('export-scenario').disabled=true;$('scenario-table').replaceChildren();}}
$('economics-form').addEventListener('input',calculate);$('economics-form').addEventListener('submit',e=>e.preventDefault());$('economics-form').addEventListener('reset',e=>{e.preventDefault();for(const[k,v]of Object.entries(E.defaults))$(k).value=v;calculate();});document.querySelectorAll('[data-members]').forEach(button=>button.addEventListener('click',()=>{$('members').value=button.dataset.members;calculate();}));calculate();
function compare(){const v=E.totalCost($('period').value);put('project-total',money(v.project));put('subscription-total',money(v.subscription));put('tco-saving',money(Math.abs(v.saving)));put('tco-copy',v.saving>=0?`menos de costo total con la membresía en ${v.months} meses.`:`menos de costo total con el proyecto separado en ${v.months} meses.`);$('comparison-result').classList.toggle('alternative',v.saving<0);}$('period').addEventListener('change',compare);compare();
function calcSupport(){try{const v=E.support(Object.fromEntries(['resolved','minutes','supervision','hourly'].map(k=>[k,$(k).value])));$('support-error').hidden=true;$('support-result').hidden=false;put('hours-saved',decimal(v.netHours)+' h');$('hours-saved').classList.toggle('negative',v.netHours<0);put('capacity-value',money(v.capacity));$('capacity-value').classList.toggle('negative',v.capacity<0);put('support-formula',`${decimal(v.resolved)} × ${decimal(v.minutes)} min ÷ 60 − ${decimal(v.supervision)} h de supervisión = ${decimal(v.netHours)} h netas.${v.netHours<0?' La supervisión supera las horas evitadas; no hay ahorro de capacidad.':''}`);}catch(e){put('support-error',e.message);$('support-error').hidden=false;$('support-result').hidden=true;}}$('support-form').addEventListener('input',calcSupport);$('support-form').addEventListener('submit',e=>e.preventDefault());calcSupport();
const demos={contenido:{title:'Un primer guion para tus termos personalizados',body:'“¿Tu café se enfría antes de terminar tu mañana? Presenta tu termo, muestra una característica comprobada y cierra invitando a conocer los diseños disponibles.” Un borrador que el miembro revisa y adapta.',next:'Del primer borrador a tu calendario de contenido.',copy:'Conoce PRO Creador para seguir preparando piezas con el contexto de tu negocio y dentro de los límites del plan.',href:'#membresias',link:'Ver propuesta PRO'},guia:{title:'Un siguiente paso, no toda la academia de golpe',body:'Ejemplo: define a quién quieres ayudar, describe una necesidad concreta y prepara una primera propuesta. El asistente puede orientar hacia referencias del catálogo; un título no demuestra la enseñanza de una lección.',next:'Primero orientación. Después una invitación pertinente.',copy:'Para prospectos: revisar la oferta oficial de BeGlobal. Para miembros: evaluar el complemento PRO Guía. No ofrecer otra membresía para resolver un problema de acceso.',href:'https://www.beglobalpro.org/membresias',link:'Ver membresías actuales de BeGlobal ↗'},voz:{title:'Una conversación para aclarar el próximo paso',body:'Ejemplo de recorrido: el visitante inicia voluntariamente una conversación, comparte su etapa y recibe orientación breve. Si necesita ayuda humana, el asistente debe derivar con contexto y consentimiento.',next:'Descubrir la experiencia de voz.',copy:'El enlace abre la página Vapi existente. Esta presentación no inicia llamadas ni verifica aquí su facturación o disponibilidad. La prueba acotada descrita aún debe implementarse.',href:'/vapi/',link:'Abrir experiencia Vapi existente ↗'}};
document.querySelectorAll('[data-demo]').forEach(button=>button.addEventListener('click',()=>{const d=demos[button.dataset.demo];document.querySelectorAll('[data-demo]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});for(const[k,v]of Object.entries(d)){if(!['href','link'].includes(k))put('demo-'+k,v);}put('demo-link',d.link);$('demo-link').href=d.href;if(d.href.startsWith('#')){$('demo-link').removeAttribute('target');$('demo-link').removeAttribute('rel');}else{$('demo-link').target='_blank';$('demo-link').rel='noopener noreferrer';}$('demo-dismissed').hidden=true;$('demo-dismiss').hidden=false;}));$('demo-dismiss').addEventListener('click',()=>{$('demo-dismissed').hidden=false;$('demo-dismiss').hidden=true;});
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);put('toast','Descarga preparada. No se envió información ni se registró una aprobación.');$('toast').hidden=false;setTimeout(()=>{$('toast').hidden=true;},6000);}
$('export-scenario').addEventListener('click',()=>{if(!currentModel)return;download('beglobal-escenario.json',JSON.stringify({proposal_version:'2026-09-08-v1',created_at:new Date().toISOString(),currency:'MXN',taxes_included:false,scenario_not_forecast:true,approval_recorded:false,assumptions:readForm(),results:currentModel,total_cost_comparison:E.totalCost($('period').value),notes:['Costos estimados, no observados.','Participaciones antes de impuestos y ajuste contractual.','La cuota corporativa se muestra aparte.','No se modela adquisición, bajas ni escalamiento de costos fijos.']},null,2),'application/json');});
$('download-brief').addEventListener('click',()=>{const lines=['# BeGlobal × Softvibes · Propuesta ejecutiva','','Propuesta para revisión. Precios en MXN antes de impuestos. No constituye aprobación ni contrato.','','## Oferta corporativa','','- Atención Digital: $9,900/mes; 2,000 respuestas IA en web.','- Asesor Vapi: $14,900/mes; 1,000 minutos de voz web.','- Integral: $19,900/mes; ambas cuotas. Incluye uso de las probaditas.','- Activación estándar sin cobro inicial con compromiso propuesto de 12 meses.','- Una marca y sitio; actualización mensual hasta 4 h por paquete.','- WhatsApp, telefonía, CRM, campañas, producción audiovisual y personalización: aparte.','','## Membresías adicionales propuestas','','- PRO Guía: $499/mes por usuario; 100 respuestas.','- PRO Creador: $999/mes por usuario; 300 respuestas.','- PRO Negocio: $1,999/mes por usuario; 800 respuestas.','- No sustituyen la academia ni operan cuentas. Activación estándar incluida.','','## Activación y comparación','','Proyecto separado propuesto: $65,000 iniciales + $14,900/mes.','Integral con activación incluida: $0 iniciales + $19,900/mes.','En 12 meses: $243,800 vs $238,800. Se evita el desembolso inicial de $65,000; el ahorro total ilustrativo es $5,000.','No es un descuento histórico ni una promesa de menor costo a largo plazo.','','## Escenario editado','','No es una previsión de ventas.'];if(currentModel){const m=currentModel;lines.push(`Miembros: ${m.members}; ticket medio: ${money(m.ticket)}; costo variable: ${money(m.variable)}; costos fijos: ${money(m.fixed)}; reserva: ${m.reserve}%.`,`Ingresos: ${money(m.revenue)}; resultado operativo antes de impuestos: ${money(m.profit)}.`,`Participaciones teóricas: BeGlobal ${m.share}% = ${money(m.beglobal)}; Softvibes ${100-m.share}% = ${money(m.softvibes)}.`,`Participación BeGlobal menos cuota Integral: ${money(m.netBeglobal)}.`,`Equilibrio: ${m.breakEven===null?'no alcanzable':m.breakEven+' miembros'}.`);}else lines.push('Sin escenario válido; corregir entradas en el simulador.');lines.push('','## Antes de lanzar','','Aprobar alcance, contenido, precios y reparto. Verificar agentes y facturación. Implementar autenticación, aislamiento, límites y cobro. Acordar financiación, pérdidas y cancelación.','50 cursos y 1,181 referencias; solo 94 lecciones con ASR local en el corte analizado.','Piloto acotado; no garantía de ingresos, ahorro de nómina ni resultados.','','Presentación: https://beglobal.softvibes.pro/propuesta/','Fuente de costos de voz: https://vapi.ai/pricing','');download('beglobal-resumen-ejecutivo.md',lines.join('\n'),'text/markdown;charset=utf-8');});
$('print').addEventListener('click',()=>window.print());
const sections=[...document.querySelectorAll('[data-slide]')],nav=[...document.querySelectorAll('.sidebar nav a')];let active=0,presenting=false;
function updateActive(){let chosen=0;for(let i=0;i<sections.length;i++){if(sections[i].getBoundingClientRect().top<=180)chosen=i;}active=chosen;nav.forEach((link,i)=>{if(i===active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});put('slide-counter',`${active+1} / ${sections.length}`);$('previous').disabled=active===0;$('next').disabled=active===sections.length-1;}
let frame=false;window.addEventListener('scroll',()=>{if(!frame){requestAnimationFrame(()=>{updateActive();frame=false;});frame=true;}},{passive:true});
function mode(on){presenting=on;document.body.classList.toggle('presentation',on);$('present').setAttribute('aria-pressed',String(on));put('present',on?'Salir de presentación':'Modo presentación');$('presentation-controls').hidden=!on;$('navigation').classList.remove('open');$('menu').setAttribute('aria-expanded','false');updateActive();}
$('present').addEventListener('click',()=>mode(!presenting));$('exit-presentation').addEventListener('click',()=>mode(false));function move(delta){active=Math.max(0,Math.min(sections.length-1,active+delta));sections[active].scrollIntoView({behavior:'instant'});updateActive();}$('previous').addEventListener('click',()=>move(-1));$('next').addEventListener('click',()=>move(1));document.addEventListener('keydown',e=>{if(e.key==='Escape'){mode(false);$('navigation').classList.remove('open');$('menu').setAttribute('aria-expanded','false');}if(!presenting||/INPUT|SELECT|TEXTAREA|AUDIO/.test(e.target.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}});
$('menu').addEventListener('click',()=>{const open=$('navigation').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open));});nav.forEach(link=>link.addEventListener('click',()=>{$('navigation').classList.remove('open');$('menu').setAttribute('aria-expanded','false');}));document.addEventListener('click',e=>{if(!e.target.closest('.sidebar')&&!e.target.closest('#menu')){$('navigation').classList.remove('open');$('menu').setAttribute('aria-expanded','false');}});updateActive();
})();
