(function(root){
  'use strict';
  const defaults=Object.freeze({members:100,ticket:899,variable:180,fixed:18000,reserve:5,share:40});
  function numeric(v,name,min,max,integer=false){if(v===''||v===null||v===undefined||typeof v==='boolean')throw new Error('Completa '+name+'.');const n=Number(v);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw new Error('Revisa '+name+': valor fuera del rango permitido.');return n;}
  function program(raw){const p={members:numeric(raw.members,'miembros',0,10000,true),ticket:numeric(raw.ticket,'ingreso medio',1,100000),variable:numeric(raw.variable,'costo variable',0,100000),fixed:numeric(raw.fixed,'costos fijos',0,10000000),reserve:numeric(raw.reserve,'reserva',0,100),share:numeric(raw.share,'participación',0,100)};const revenue=p.members*p.ticket,variableTotal=p.members*p.variable,reserveTotal=revenue*p.reserve/100,profit=revenue-variableTotal-reserveTotal-p.fixed,distributable=Math.max(0,profit),beglobal=distributable*p.share/100,softvibes=distributable-beglobal,perMember=p.ticket*(1-p.reserve/100)-p.variable;return{...p,revenue,variableTotal,reserveTotal,profit,beglobal,softvibes,perMember,breakEven:perMember>0?Math.ceil(p.fixed/perMember):null,netBeglobal:beglobal-19900};}
  function totalCost(months){months=numeric(months,'periodo',1,120,true);return{months,initialAvoided:65000,project:65000+14900*months,subscription:19900*months,saving:65000-5000*months};}
  function support(raw){const resolved=numeric(raw.resolved,'consultas',0,100000,true),minutes=numeric(raw.minutes,'minutos por consulta',0,240),supervision=numeric(raw.supervision,'supervisión',0,10000),hourly=numeric(raw.hourly,'costo por hora',0,100000);const grossHours=resolved*minutes/60,netHours=grossHours-supervision;return{resolved,minutes,supervision,hourly,grossHours,netHours,capacity:netHours*hourly};}
  const api={defaults,program,totalCost,support};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BeGlobalEconomics=api;
})(typeof globalThis!=='undefined'?globalThis:this);
