"use strict";
const assert = require("node:assert/strict");
const { after, before, test } = require("node:test");
const { spawn } = require("node:child_process");
const http = require("node:http");
const path = require("node:path");
const port = 18655;
const upstreamPort = 18656;
const origin = "https://chatbeglobal.softvibes.pro";
let app;
let upstream;
let lastRequest;
async function waitFor(url) { for (let i=0;i<40;i+=1) { try { if ((await fetch(url)).ok) return; } catch {} await new Promise(r=>setTimeout(r,100)); } throw new Error("not ready"); }
function cookieFrom(response) { return response.headers.get("set-cookie").split(";")[0]; }
async function createSession(ip="203.0.113.10") {
  const response = await fetch(`http://127.0.0.1:${port}/api/session`, { method:"POST", headers:{ Origin:origin, "X-Forwarded-For":ip, "Content-Type":"application/json" }, body:"{}" });
  return { response, cookie:cookieFrom(response), csrf:(await response.json()).csrf };
}
before(async()=>{
  upstream=http.createServer(async(req,res)=>{ const chunks=[]; for await(const c of req) chunks.push(c); lastRequest={headers:req.headers,body:JSON.parse(Buffer.concat(chunks))}; const userMessage=lastRequest.body.messages.at(-1)?.content||""; if(userMessage.includes("SIMULAR_FALLO_HERMES")){res.writeHead(500,{"Content-Type":"application/json"});return res.end(JSON.stringify({error:"simulated"}));} const content=userMessage==="Continuemos."?"Tu misión inicial: valida una idea con tres clientes y registra la evidencia de avance.":userMessage==="Revisa lo anterior."?"Aquí tienes tu diagnóstico: la propuesta necesita una evidencia comercial.":userMessage==="¿Qué significa la palabra diagnóstico?"?"Un diagnóstico es una evaluación para entender la situación y definir el siguiente paso.":"Respuesta pública segura"; res.writeHead(200,{"Content-Type":"application/json"}); res.end(JSON.stringify({choices:[{message:{content}}]})); });
  await new Promise(r=>upstream.listen(upstreamPort,"127.0.0.1",r));
  app=spawn(process.execPath,["server.js"],{cwd:path.resolve(__dirname,".."),env:{...process.env,PORT:String(port),HOST:"127.0.0.1",HERMES_BASE_URL:`http://127.0.0.1:${upstreamPort}`,API_SERVER_KEY:"test-key-with-safe-length",ALLOWED_ORIGIN:origin,IP_LIMIT_MAX:"500"}});
  await waitFor(`http://127.0.0.1:${port}/healthz`);
});
after(async()=>{app?.kill("SIGTERM");if(upstream)await new Promise(r=>upstream.close(r));});
test("serves iframe-safe shell",async()=>{const r=await fetch(`http://127.0.0.1:${port}/`);const h=await r.text();assert.equal(r.status,200);assert.match(r.headers.get("content-security-policy"),/frame-ancestors https:\/\/beglobal\.softvibes\.pro/);assert.match(h,/Be Global Asistente/);});
test("requires exact origin to create session",async()=>{const r=await fetch(`http://127.0.0.1:${port}/api/session`,{method:"POST",headers:{Origin:"https://evil.example"}});assert.equal(r.status,403);});
test("uses HttpOnly cookie, CSRF and fixed profile",async()=>{const s=await createSession();assert.equal(s.response.status,201);assert.match(s.response.headers.get("set-cookie"),/HttpOnly; Secure; SameSite=Lax/);const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"¿Qué es Be Global?"})});assert.equal(r.status,200);assert.deepEqual(await r.json(),{message:"Respuesta pública segura"});assert.equal(lastRequest.body.model,"beglobalasistente");assert.deepEqual(lastRequest.body.messages,[{role:"user",content:"¿Qué es Be Global?"}]);assert.match(lastRequest.headers["x-hermes-session-key"],/^web:/);});
test("rejects client model and role overrides",async()=>{const s=await createSession("203.0.113.11");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"hola",model:"otro",role:"system"})});assert.equal(r.status,400);});
test("does not accept another session without its CSRF",async()=>{const a=await createSession("203.0.113.12");const b=await createSession("203.0.113.13");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:a.cookie,"X-BeGlobal-CSRF":b.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"hola"})});assert.equal(r.status,403);});
test("offers the governed membership CTA after a mission",async()=>{const s=await createSession("203.0.113.14");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Dame mi misión inicial para comenzar a vender"})});assert.equal(r.status,200);assert.deepEqual(await r.json(),{message:"Respuesta pública segura",cta:{type:"membership",title:"¿Quieres acompañamiento para ejecutar tu misión?",text:"Explora las opciones vigentes de Be Global Pro y elige con calma la que mejor corresponda a tu etapa.",label:"Ver membresías",url:"https://www.beglobalpro.org/membresias"}});});
test("does not add a sales CTA to a general first answer",async()=>{const s=await createSession("203.0.113.15");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"¿Qué es Be Global?"})});assert.deepEqual(await r.json(),{message:"Respuesta pública segura"});});
test("respects an explicit request not to receive purchase offers",async()=>{const s=await createSession("203.0.113.16");const no=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"No quiero comprar, solo quiero información"})});assert.deepEqual(await no.json(),{message:"Respuesta pública segura"});const mission=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Ahora dame una misión inicial"})});assert.deepEqual(await mission.json(),{message:"Respuesta pública segura"});});
test("recognizes natural-language sales opt-outs",async()=>{for(const [index,message] of ["No deseo recibir ofertas","No quiero ofertas","No vuelvas a ofrecerme membresías","No me interesa recibir promociones","No más ofertas","Déjame de ofrecer membresías"].entries()){const s=await createSession(`203.0.114.${index + 1}`);const no=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message})});assert.deepEqual(await no.json(),{message:"Respuesta pública segura"});const mission=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Dame una misión para vender"})});assert.deepEqual(await mission.json(),{message:"Respuesta pública segura"});}});
test("shows the contextual CTA once instead of repeating it",async()=>{const s=await createSession("203.0.113.17");const first=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Ayúdame a empezar con una misión"})});assert.ok((await first.json()).cta);const second=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Ahora ayúdame con mi tienda"})});assert.deepEqual(await second.json(),{message:"Respuesta pública segura"});});
test("does not sell during account or refund support",async()=>{const s=await createSession("203.0.113.18");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Ya soy miembro y necesito un reembolso de mi membresía"})});assert.deepEqual(await r.json(),{message:"Respuesta pública segura"});});
test("does not add a CTA to common support, billing or affordability incidents",async()=>{for(const [index,message] of ["Necesito soporte con mi tienda","Tengo un problema con el pago de mi membresía","Quiero una devolución","Me hicieron un cobro incorrecto","Me cobraron de más por la membresía","No puedo pagar la membresía","Necesito ayuda con un cobro de mi cuenta"].entries()){const s=await createSession(`203.0.115.${index + 1}`);const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message})});assert.deepEqual(await r.json(),{message:"Respuesta pública segura"});}});
test("keeps normal sales questions eligible when cobro is not an incident",async()=>{const s=await createSession("203.0.115.9");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"¿Cómo organizo el cobro en mi tienda?"})});assert.ok((await r.json()).cta);});
test("never repeats the CTA after an explicit membership follow-up",async()=>{const s=await createSession("203.0.116.1");const first=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Quiero adquirir una membresía"})});assert.ok((await first.json()).cta);const second=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"¿Qué precio tiene la membresía?"})});assert.deepEqual(await second.json(),{message:"Respuesta pública segura"});});
test("offers the CTA when Hermes actually delivers a mission after a neutral prompt",async()=>{const s=await createSession("203.0.116.2");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Continuemos."})});const body=await r.json();assert.match(body.message,/Tu misión inicial/);assert.ok(body.cta);});
test("offers the CTA when Hermes actually delivers a diagnosis after a neutral prompt",async()=>{const s=await createSession("203.0.116.5");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Revisa lo anterior."})});const body=await r.json();assert.match(body.message,/tu diagnóstico/);assert.ok(body.cta);});
test("does not treat a conceptual diagnosis question as a completed diagnosis",async()=>{const s=await createSession("203.0.116.3");const r=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"¿Qué significa la palabra diagnóstico?"})});assert.deepEqual(await r.json(),{message:"Un diagnóstico es una evaluación para entender la situación y definir el siguiente paso."});});
test("persists opt-out even when Hermes fails on that turn",async()=>{const s=await createSession("203.0.116.4");const failed=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"No quiero ofertas. SIMULAR_FALLO_HERMES"})});assert.equal(failed.status,502);const mission=await fetch(`http://127.0.0.1:${port}/api/chat`,{method:"POST",headers:{Origin:origin,Cookie:s.cookie,"X-BeGlobal-CSRF":s.csrf,"Content-Type":"application/json"},body:JSON.stringify({message:"Dame una misión para vender"})});assert.deepEqual(await mission.json(),{message:"Respuesta pública segura"});});
test("frontend renders text and only the fixed membership destination",async()=>{const r=await fetch(`http://127.0.0.1:${port}/app.js`);const script=await r.text();assert.match(script,/article\.textContent = text/);assert.match(script,/https:\/\/www\.beglobalpro\.org\/membresias/);assert.match(script,/function appendCta/);assert.doesNotMatch(script,/innerHTML/);});
