const {chromium,expect}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const baseURL=process.env.PROPOSAL_URL||'http://127.0.0.1:8769/';
const artifacts=fs.mkdtempSync('/tmp/beglobal-propuesta-test.');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try{for(const width of[1440,390]){const context=await browser.newContext({viewport:{width,height:1000},acceptDownloads:true,reducedMotion:'reduce'});const page=await context.newPage();const errors=[],failed=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(baseURL))external.push(r.url());});
await page.goto(baseURL);await expect(page.getByRole('heading',{level:1})).toContainText('Una primera ayuda.');await expect(page.locator('h1')).toHaveCount(1);await expect(page.getByRole('link',{name:/Explorar la propuesta/})).toBeVisible();
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:path.join(artifacts,`hero-${width}.png`)});
if(width<960){await page.getByRole('button',{name:/Menú/}).click();await expect(page.getByRole('navigation',{name:'Secciones de la presentación'})).toBeVisible();await page.getByRole('navigation').getByRole('link',{name:/De prueba a membresía/}).click();}
await page.getByRole('button',{name:/Descubre tu próximo paso/}).click();await expect(page.locator('#demo-title')).toContainText('Un siguiente paso');await expect(page.locator('#demo-link')).toHaveAttribute('href','https://www.beglobalpro.org/membresias');await page.getByRole('button',{name:'Ahora no',exact:true}).click();await expect(page.locator('#demo-dismissed')).toBeVisible();await page.getByRole('button',{name:/Crea tu primer guion/}).click();await expect(page.locator('#demo-title')).toContainText('termos');await expect(page.getByRole('button',{name:'Ahora no',exact:true})).toBeVisible();
await page.getByLabel('Periodo',{exact:true}).selectOption('24');await expect(page.locator('#project-total')).toHaveText('$422,600');await expect(page.locator('#subscription-total')).toHaveText('$477,600');await expect(page.locator('#tco-saving')).toHaveText('$55,000');await expect(page.locator('#tco-copy')).toContainText('proyecto separado');await page.getByLabel('Periodo',{exact:true}).selectOption('12');await expect(page.locator('#tco-saving')).toHaveText('$5,000');
await expect(page.locator('#profit')).toHaveText('$49,405');await page.getByRole('button',{name:'300 miembros',exact:true}).click();await expect(page.locator('#revenue')).toHaveText('$269,700');await expect(page.locator('#profit')).toHaveText('$184,215');await page.getByLabel('Miembros de pago',{exact:true}).fill('0');await expect(page.locator('#profit')).toHaveText('-$18,000');await expect(page.locator('#beglobal-share')).toHaveText('$0');
await page.getByLabel('Miembros de pago',{exact:true}).fill('');await expect(page.locator('#model-error')).toBeVisible();await expect(page.getByRole('button',{name:'Descargar escenario JSON'})).toBeDisabled();await page.getByRole('button',{name:'Restablecer',exact:true}).click();await expect(page.locator('#revenue')).toHaveText('$89,900');
await page.getByLabel('Costo variable / miembro (MXN)',{exact:true}).fill('999');await expect(page.locator('#break-even')).toContainText('No alcanzable');await page.getByRole('button',{name:'Restablecer',exact:true}).click();
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar escenario JSON'}).click();const download=await downloadPromise;const data=JSON.parse(fs.readFileSync(await download.path(),'utf8'));expect(data.results.profit).toBe(49405);expect(data.approval_recorded).toBe(false);
await page.locator('#escenarios').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifacts,`economics-${width}.png`)});
await expect(page.locator('#hours-saved')).toHaveText('40 h');await page.getByLabel('Consultas realmente resueltas / mes',{exact:true}).fill('0');await expect(page.locator('#hours-saved')).toHaveText('-10 h');await expect(page.locator('#capacity-value')).toHaveText('-$2,000');await page.getByLabel('Consultas realmente resueltas / mes',{exact:true}).fill('300');
await page.getByRole('button',{name:'Modo presentación',exact:true}).click();await expect(page.locator('body')).toHaveClass(/presentation/);await expect(page.getByRole('button',{name:'Sección siguiente'})).toBeVisible();await page.getByRole('button',{name:'Salir',exact:true}).click();await expect(page.locator('body')).not.toHaveClass(/presentation/);
const briefPromise=page.waitForEvent('download');await page.getByRole('button',{name:/Descargar resumen ejecutivo/}).click();const brief=await briefPromise;expect(fs.readFileSync(await brief.path(),'utf8')).toContain('No constituye aprobación');
await page.getByText('¿La implementación es realmente gratis?',{exact:true}).click();await expect(page.getByText('No tiene cobro inicial separado',{exact:false})).toBeVisible();
const audio=page.locator('audio');await audio.scrollIntoViewIfNeeded();await audio.evaluate(el=>{el.load();});await expect.poll(()=>audio.evaluate(el=>Number.isFinite(el.duration)?el.duration:0),{timeout:20000}).toBeGreaterThan(440);await expect.poll(()=>audio.evaluate(el=>el.duration)).toBeLessThan(455);expect(await audio.evaluate(el=>el.paused)).toBe(true);
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();expect(errors).toEqual([]);expect(failed).toEqual([]);expect(external).toEqual([]);
if(width===1440){await page.emulateMedia({media:'print'});await page.pdf({path:path.join(artifacts,'propuesta.pdf'),format:'A4',printBackground:true});}
results.push({width,calculators:true,negative_scenarios:true,demos:true,downloads:true,presentation_mode:true,podcast_metadata:true,horizontal_overflow:false,page_errors:errors.length});await context.close();}
const result={status:'passed',baseURL,artifacts,results};fs.writeFileSync(path.join(artifacts,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
